version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 4.2.0
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: truffle
    versions:
    - 5.1.63
    - 5.1.64
    - 5.1.65
    - 5.1.66
    - 5.1.67
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
    - 5.3.0
    - 5.3.1
    - 5.3.2
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.6.0
  - dependency-name: solc
    versions:
    - 0.8.1
    - 0.8.2
    - 0.8.3
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.0
  - dependency-name: style-loader
    versions:
    - 1.2.1
  - dependency-name: babel-loader
    versions:
    - 8.1.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.2.1
